services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend
  backend:
    container_name: backend
    image: python:3.13-alpine
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/my_db
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app # Monta o código do backend para desenvolvimento.
    depends_on:
      - db
  db:
    container_name: postgres_db
    image: postgres:17.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: